export {PatientModel} from './patient.model'
export {TestModel} from './test.model'
export {AnswerModel} from './answer.model'
export {QuestionModel} from './question.model'
export {ResultModel} from './result.model'
